apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-uploads
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0001/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-uploads
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: uploads
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0002/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
