kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-uploads
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"
